
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: osint
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/test
    ports:
      - "7474:7474"
      - "7687:7687"

  api:
    build: 
      context: .
      dockerfile: services/api/Dockerfile
    env_file:
      - ./envs/api.env
    ports:
      - "8000:8000"
    volumes:
      - ./services/api/app:/app
    depends_on:
      - postgres
      - redis
      - minio

  worker:
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    env_file:
      - ./envs/worker.env
    volumes:
      - ./services/worker/tasks:/app/tasks
    depends_on:
      - postgres
      - redis
      - minio

volumes:
  pgdata:
  miniodata:
